#!/bin/bash

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


install -dm755 /usr/bin/
install -dm755 /opt/adaptigo/

install -Dpm 0755 adaptigo.exec /usr/bin/adaptigo
install -Dpm 0755 adaptigo /opt/adaptigo/adaptigo
install -Dpm 0755 app.js /opt/adaptigo/app.js
install -dm755 /opt/adaptigo/
install -Dpm 0755 bin/run-as-root /opt/adaptigo/bin/run-as-root
install -Dpm 0755 bin/run-as-user /opt/adaptigo/bin/run-as-user
install -Dpm 0644 adaptigo.desktop /usr/share/applications/adaptigo.desktop
install -Dpm 0644 adaptigo.appdata.xml /usr/share/appdata/adaptigo.appdata.xml

install -Dpm 0644 adaptigo.svg /usr/share/icons/hicolor/scalable/apps/adaptigo.svg
install -Dpm 0644 adaptigo-symbolic.svg /usr/share/icons/hicolor/scalable/apps/adaptigo-symbolic.svg

install -Dpm 0644 run-as-root.policy /usr/share/polkit-1/actions/run-as-root.policy

gtk-update-icon-cache -f -t /usr/share/icons/hicolor
rm -Rfv /opt/adaptigo/plugins/
install -dm755 /opt/adaptigo/plugins
cp -pr plugins/* /opt/adaptigo/plugins/
