#!/bin/bash

# Script to install Fedy <http://satya164.github.io/fedy/>.
# Copyright (C) 2014  Satyajit sahoo

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


