#!/bin/bash

if [[ ! $(whoami) = "root" ]]; then
    echo "Please run the script as root."
    exit 1
fi


install -dm755 /usr/bin/
install -dm755 /opt/debbie//

install -Dpm 0755 debbie.exec /usr/bin/debbie
install -Dpm 0755 debbie /opt/debbie/debbie
install -Dpm 0755 app.js /opt/debbie/app.js
install -dm755 /opt/debbie/
install -Dpm 0755 bin/run-as-root /opt/debbie/bin/run-as-root
install -Dpm 0755 bin/run-as-user /opt/debbie/bin/run-as-user
install -Dpm 0644 debbie.desktop /usr/share/applications/debbie.desktop
install -Dpm 0644 debbie.appdata.xml /usr/share/appdata/debbie.appdata.xml

install -Dpm 0644 debbie.svg /usr/share/icons/hicolor/scalable/apps/debbie.svg
install -Dpm 0644 debbie-symbolic.svg /usr/share/icons/hicolor/scalable/apps/debbie-symbolic.svg

install -Dpm 0644 run-as-root.policy /usr/share/polkit-1/actions/run-as-root.policy

gtk-update-icon-cache -f -t /usr/share/icons/hicolor
rm -Rfv /opt/debbie/plugins/
install -dm755 /opt/debbie/plugins
cp -pr plugins/* /opt/debbie/plugins/
